[tool.isort]
profile = "black"         # هماهنگی با black
line_length = 120
combine_as_imports = true # ترکیب import های مشابه
force_single_line = false # جلوگیری از تک‌خطی‌کردن اجباری

[tool.black]
line-length = 120
target-version = ["py310"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/  # جلوگیری از فرمت‌کردن فایل‌های غیرمرتبط
'''

[tool.mypy]
files = ["src/"]
ignore_missing_imports = true # نادیده‌گرفتن import های نامشخص
strict = true                 # فعال‌کردن بررسی‌های سخت‌گیرانه
warn_unused_ignores = true
show_error_codes = true
follow_imports = "normal"
disallow_untyped_defs = false


[tool.pyright]
typeCheckingMode = "basic"
reportUnusedImport = "none"      # غیرفعال‌کردن هشدارهای import های بلااستفاده
reportUnusedVariable = "warning" # هشدار برای متغیرهای بلااستفاده


[tool.pylint]
disable = ["C0116", "C0114"]
